### PR TITLE
Config update in background

### PR DESCRIPTION
**Pull request by anshumansworld**
This include modifications related to cofig download in background. Now developers will call init() method with passing APP_TOKEN & extra data(optional) that will lead to download config immediately so that at the time of request it can serve ad as fast as it can.

### CODE REVIEW

**Comment by RagnarR** [comment]
Mostly looks good. One thing what I worrying about - this Service will start in main thread.

**Comment by anshumansworld** [comment]
That will not impact app because downloading part is in another thread that is being created in `PubnativeHttpRequest`

**Comment by RagnarR** [comment]
Make sense 👍

**Comment by cerberillo** [comment]
Let's reopen this branch to improve it

**Comment by cerberillo** [comment]
I would like this to do it by subclassing, instead of using a separate Pubnative class, let's make all the units inherit from this and have the init method that starts any possible common behaviour on app start

**Comment by RagnarR** [comment]
@cerberillo mmm. I think will make our app complicated. We already have a big inheritance. This variant clear for me and you can use it through `Pubnative.init()` at the start of your app for warming up. Btw, it could contain other useful initialization in Future. And also one, we discussed with Amir behavior of this background service and we decide that it must update config from time to time if the user initiates it.
For the second one - better create separated improvement task for it and discuss it separately.

**Comment by cerberillo** [comment]
Let's discuss this on monday.

another thing is that there is not documentation for this in the README file and it's not being used in the demo app properly, and we should, not just as an example, but as a test for us

**Pull request merged**
